In [1]:
import pandas as pd
import numpy as np
import random
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
df=pd.read_csv("df.csv")

In [3]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  label  
0                  0.2654          0.4601                  0.11890      0  
1                  0.1860          0.2750                  0.08902      0  
2                  0.2430          0.3613                  0.08758      0  
3                  0.2575          0.6638                  0.17300      0  
4                  0.1625          0.2364                  0.07678   

In [4]:
df['label'].value_counts()

1    357
0    212
Name: label, dtype: int64

In [5]:
from tensorflow.keras.utils import to_categorical

In [6]:
y_data=to_categorical(df['label'])
y_data

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [7]:
X_data = df.iloc[:,:-1]
X_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()
X_data_scaled = scaler.fit_transform(X_data)
X_data_scaled

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_data_scaled, y_data, 
                                                    test_size=0.1, 
                                                    shuffle=True, 
                                                    random_state=11)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(512, 30) (512, 2)
(57, 30) (57, 2)


In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential()##Layer 쌓을 수 있도록 객체를 생성 
model.add(Dense(128, activation='relu', input_dim=30))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(2, activation='softmax'))

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc','mae'])
#이 모델로 설정을 하겠음.
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               3968      
                                                                 
 dense_1 (Dense)             (None, 32)                4128      
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 8,162
Trainable params: 8,162
Non-trainable params: 0
_________________________________________________________________


In [14]:
history = model.fit(X_train, y_train, epochs=300, batch_size=32, verbose=2)
history #401번 돌림0.8997 -

Epoch 1/300
16/16 - 1s - loss: 0.6752 - acc: 0.6172 - mae: 0.4265 - 514ms/epoch - 32ms/step
Epoch 2/300
16/16 - 0s - loss: 0.6025 - acc: 0.6680 - mae: 0.3962 - 25ms/epoch - 2ms/step
Epoch 3/300
16/16 - 0s - loss: 0.5539 - acc: 0.8691 - mae: 0.3523 - 26ms/epoch - 2ms/step
Epoch 4/300
16/16 - 0s - loss: 0.4955 - acc: 0.8965 - mae: 0.2944 - 28ms/epoch - 2ms/step
Epoch 5/300
16/16 - 0s - loss: 0.4324 - acc: 0.8965 - mae: 0.2376 - 24ms/epoch - 2ms/step
Epoch 6/300
16/16 - 0s - loss: 0.3718 - acc: 0.9160 - mae: 0.1909 - 27ms/epoch - 2ms/step
Epoch 7/300
16/16 - 0s - loss: 0.3234 - acc: 0.9102 - mae: 0.1598 - 27ms/epoch - 2ms/step
Epoch 8/300
16/16 - 0s - loss: 0.2864 - acc: 0.9336 - mae: 0.1358 - 24ms/epoch - 1ms/step
Epoch 9/300
16/16 - 0s - loss: 0.2565 - acc: 0.9199 - mae: 0.1204 - 24ms/epoch - 2ms/step
Epoch 10/300
16/16 - 0s - loss: 0.2368 - acc: 0.9277 - mae: 0.1094 - 26ms/epoch - 2ms/step
Epoch 11/300
16/16 - 0s - loss: 0.2207 - acc: 0.9336 - mae: 0.1006 - 23ms/epoch - 1ms/step
Epoch 

Epoch 92/300
16/16 - 0s - loss: 0.0472 - acc: 0.9844 - mae: 0.0171 - 26ms/epoch - 2ms/step
Epoch 93/300
16/16 - 0s - loss: 0.0504 - acc: 0.9805 - mae: 0.0217 - 25ms/epoch - 2ms/step
Epoch 94/300
16/16 - 0s - loss: 0.0552 - acc: 0.9844 - mae: 0.0187 - 23ms/epoch - 1ms/step
Epoch 95/300
16/16 - 0s - loss: 0.0508 - acc: 0.9766 - mae: 0.0214 - 26ms/epoch - 2ms/step
Epoch 96/300
16/16 - 0s - loss: 0.0464 - acc: 0.9883 - mae: 0.0175 - 28ms/epoch - 2ms/step
Epoch 97/300
16/16 - 0s - loss: 0.0478 - acc: 0.9844 - mae: 0.0168 - 25ms/epoch - 2ms/step
Epoch 98/300
16/16 - 0s - loss: 0.0453 - acc: 0.9805 - mae: 0.0177 - 27ms/epoch - 2ms/step
Epoch 99/300
16/16 - 0s - loss: 0.0465 - acc: 0.9863 - mae: 0.0187 - 26ms/epoch - 2ms/step
Epoch 100/300
16/16 - 0s - loss: 0.0451 - acc: 0.9883 - mae: 0.0157 - 26ms/epoch - 2ms/step
Epoch 101/300
16/16 - 0s - loss: 0.0497 - acc: 0.9824 - mae: 0.0200 - 26ms/epoch - 2ms/step
Epoch 102/300
16/16 - 0s - loss: 0.0474 - acc: 0.9883 - mae: 0.0156 - 22ms/epoch - 1ms/s

Epoch 181/300
16/16 - 0s - loss: 0.0258 - acc: 0.9883 - mae: 0.0127 - 23ms/epoch - 1ms/step
Epoch 182/300
16/16 - 0s - loss: 0.0274 - acc: 0.9883 - mae: 0.0125 - 24ms/epoch - 2ms/step
Epoch 183/300
16/16 - 0s - loss: 0.0303 - acc: 0.9863 - mae: 0.0136 - 25ms/epoch - 2ms/step
Epoch 184/300
16/16 - 0s - loss: 0.0271 - acc: 0.9902 - mae: 0.0124 - 18ms/epoch - 1ms/step
Epoch 185/300
16/16 - 0s - loss: 0.0249 - acc: 0.9883 - mae: 0.0116 - 21ms/epoch - 1ms/step
Epoch 186/300
16/16 - 0s - loss: 0.0240 - acc: 0.9883 - mae: 0.0107 - 23ms/epoch - 1ms/step
Epoch 187/300
16/16 - 0s - loss: 0.0291 - acc: 0.9902 - mae: 0.0127 - 22ms/epoch - 1ms/step
Epoch 188/300
16/16 - 0s - loss: 0.0249 - acc: 0.9922 - mae: 0.0105 - 24ms/epoch - 1ms/step
Epoch 189/300
16/16 - 0s - loss: 0.0232 - acc: 0.9902 - mae: 0.0107 - 27ms/epoch - 2ms/step
Epoch 190/300
16/16 - 0s - loss: 0.0237 - acc: 0.9922 - mae: 0.0099 - 24ms/epoch - 1ms/step
Epoch 191/300
16/16 - 0s - loss: 0.0231 - acc: 0.9922 - mae: 0.0107 - 20ms/epoch

Epoch 271/300
16/16 - 0s - loss: 0.0112 - acc: 0.9980 - mae: 0.0047 - 26ms/epoch - 2ms/step
Epoch 272/300
16/16 - 0s - loss: 0.0106 - acc: 0.9980 - mae: 0.0039 - 26ms/epoch - 2ms/step
Epoch 273/300
16/16 - 0s - loss: 0.0114 - acc: 0.9980 - mae: 0.0043 - 25ms/epoch - 2ms/step
Epoch 274/300
16/16 - 0s - loss: 0.0115 - acc: 0.9980 - mae: 0.0045 - 27ms/epoch - 2ms/step
Epoch 275/300
16/16 - 0s - loss: 0.0102 - acc: 0.9980 - mae: 0.0039 - 23ms/epoch - 1ms/step
Epoch 276/300
16/16 - 0s - loss: 0.0102 - acc: 0.9980 - mae: 0.0035 - 25ms/epoch - 2ms/step
Epoch 277/300
16/16 - 0s - loss: 0.0114 - acc: 0.9961 - mae: 0.0044 - 22ms/epoch - 1ms/step
Epoch 278/300
16/16 - 0s - loss: 0.0123 - acc: 0.9961 - mae: 0.0054 - 23ms/epoch - 1ms/step
Epoch 279/300
16/16 - 0s - loss: 0.0171 - acc: 0.9922 - mae: 0.0082 - 26ms/epoch - 2ms/step
Epoch 280/300
16/16 - 0s - loss: 0.0220 - acc: 0.9922 - mae: 0.0110 - 22ms/epoch - 1ms/step
Epoch 281/300
16/16 - 0s - loss: 0.0126 - acc: 0.9980 - mae: 0.0050 - 25ms/epoch

In [15]:
eva_test=model.evaluate(X_test, y_test)
eva_test 

2/2 [==============================] - 0s 3ms/step - loss: 0.0210 - acc: 1.0000 - mae: 0.0095


[0.021039623767137527, 1.0, 0.009467021562159061]

In [16]:
pred_test = model.predict(X_test)
pred_test[:5]

array([[1.0000000e+00, 1.0104066e-08],
       [1.0000000e+00, 5.5570113e-09],
       [1.0000000e+00, 6.6398065e-09],
       [1.0000000e+00, 5.5584106e-09],
       [1.0000000e+00, 5.6710139e-09]], dtype=float32)

In [17]:
y_test[:5]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [18]:
from sklearn.metrics import r2_score, confusion_matrix
R2 = r2_score(y_test, pred_test, multioutput='variance_weighted')
R2

0.9810937570886302

#### 시각화

In [19]:
y_test1=np.argmax(y_test, axis=-1)#1차원 배열로만들어주어야함
y_test1

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [20]:
Y_pred_test=np.argmax(pred_test, axis=-1)
Y_pred_test

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [21]:
conf_matrix= confusion_matrix(y_test1, Y_pred_test)
conf_matrix

array([[16,  0],
       [ 0, 41]], dtype=int64)

In [22]:
title = 'test'
cmap=plt.cm.Greens
plt.figure(figsize=(6, 6))
plt.imshow(conf_matrix, interpolation='nearest', cmap=cmap)  # , cmap=plt.cm.Greens
plt.title(title, size=12)
plt.colorbar(fraction=0.05, pad=0.05)
tick_marks = np.arange(3, 3)
plt.xticks(np.arange(3), ('0', '1', '2'))
plt.yticks(np.arange(3), ('0', '1', '2'))


fmt = 'd' 
thresh = 1
for i in range(conf_matrix.shape[0]):
    for j in range(conf_matrix.shape[1]):
        plt.text(j, i, format(conf_matrix[i, j], fmt),
                 ha="center", va="center", color="white" if conf_matrix[i, j] > thresh else "black")  #horizontalalignment

NameError: name 'plt' is not defined

In [ ]:
import matplotlib.pyplot as plt

plt.plot(y_test1,marker = 'o',label='realY')
plt.plot(Y_pred_test,marker = 'o',label='predictY')
plt.legend()

plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.plot(history.history['acc'])
plt.plot(history.history['mae'])
plt.plot(history.history['loss'])
plt.show()